spring:
  application:
    name: todo-list-app
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true